### ISSUE TITLE
Remember me and localstorage

### ISSUE THREAD

**Issue by inestyne** [larscom/ngrx-store-storagesync#4]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## What is the motivation / use case for changing the behavior?

Hey Lars, is there an example somewhere of implementing 'Remember Me' type function on this. This would simply flip the storageSync from sessionStorage to localStorage.

**Comment by larscom** [comment]
Hello,
What do you mean?

**Comment by inestyne** [comment]
I’d like to flip it from local storage to session storage at run time. Depending on whether the user selected Remember me during login.

Neubauer

**Comment by larscom** [comment]
Aha, that's not possible. You can do 2 things to maybe solve this problem:

1. (the nice way) By implementing the `shouldSync` function you can skip state sync.
https://github.com/larscom/ngrx-store-storagesync/blob/07adb7439bd7e9df78c78baac013fda9dc221f3b/projects/ngrx-store-storagesync/test/state-sync.spec.ts#L29


2. (the hacky way) Create 2 feature states and give one feature the sessionStorage and one feature the localStorage 

`[
{ stateKey: 'feature1', storageForFeature: window.sessionStorage },
{ stateKey: 'feature2', storageForFeature: window.localStorage }
]`

The problem is, you can't change metareducers at runtime. Suggestions are welcome :smiley:

**Comment by inestyne** [comment]
Thanks Lars! 

Neubauer

**Comment by larscom** [comment]
No problem. Good luck!
